name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME used in Arc controller
    runs-on: custom-ci-self-runner-medium
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
